debuging compilers on macos ci
- also added ignore for vim temporals
- issue #12

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -27,6 +27,13 @@ jobs:
           fi
           pip install meson
 
+      - name: Debug env
+        run: |
+          echo "Listing compilers:"
+          ls /usr/local/bin | grep gfortran || echo "gfortran not found"
+          echo "Available packages:"
+          brew search fortran
+
       - name: Configure project with Meson
         run: meson setup --buildtype=release builddir 
 
